export const HAT_DATA = [
    {
        id: 'hat-1',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product0.jpg',
        ratting: 3,
        countOfRatting: 2,
        to: '/product/hat-1',
    },
    {
        id: 'hat-2',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product1.jpg ',
        ratting: 3,
        countOfRatting: 2,
        to: '/product/hat-2',
    },
    {
        id: 'hat-3',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product2.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/hat-3',
    },
    {
        id: 'hat-4',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product3.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/hat-4',
    },
    {
        id: 'hat-5',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product4.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/hat-5',
    },
    {
        id: 'hat-6',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product5.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/hat-6',
    },
    {
        id: 'new-hat-1',
        nameProduct: 'Classic Cap make logo',
        price: 199000,
        image: '/assets/imageProduct/product6.jpg ',
        ratting: 4.8,
        countOfRatting: 10,
        to: '/product/new-hat-1',
        features: [
            'Material 65% Cotton, 35% Polyester',
            'Unique design embroidered on the front of the hat stands out',
            'Suitable for: any daily activity',
            'Narrow brim: Hat circumference 60cm',
        ],
    },
];

export const NIKE_DATA = [
    {
        id: 'nike-1',
        nameProduct: 'Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product7.jpg ',
        ratting: 3,
        countOfRatting: 100,
        to: '/product/nike-1',
        features: [
            'Nike Air Force 1 Low LE GS All White - "bridge" between the past and the present. The long-standing values of the Air Force 1 line of shoes are clearly reflected in the sole: embossed pentagram, concentric circles to increase traction and the famous Air sole technology from years old. 1979. On the other hand, the shoes bring a fresh feeling with low neck, minimalist white tones combined with modern cut lines in the upper. Too great for a versatile shoe, right? Visit Dee Store to own a pair right away!',        ],
    },
    {
        id: 'nike-2',
        nameProduct: 'Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product8.jpg ',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/nike-2',
    },
    {
        id: 'nike-3',
        nameProduct: 'Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product9.jpg ',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/nike-3',
    },
    {
        id: 'nike-4',
        nameProduct: 'Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product10.jpg',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/nike-4',
    },
    {
        id: 'nike-5',
        nameProduct: 'Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product11.jpg',
        ratting: 2,
        countOfRatting: 100,
        to: '/product/nike-5',
    },
];

export const ADIDAS_DATA = [
    {
        id: 'adidas-1',
        nameProduct: 'Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product12.jpg',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/adidas-1',
        features: [
            'Optimized design for movement, rounded, slim toe, creating a soft, snug, comfortable feel for the foot.',
            'Anti-bent, anti-collision with heel, reduce injury, increase bounce.',
            'Using high technology in manufacturing with high-quality materials makes the shoes timeless.',
            'The designs are not only for sports but also for fashion and style elements.',
            'Easy to coordinate with outfits',
            'Regardless of gender in terms of style, both men and women when wearing genuine Adidas shoes exalt their youth, dynamism and express their own fashion style.',
        ],
    },
    {
        id: 'adidas-2',
        nameProduct: 'Adidas Neo Grand Court K EF0103',
        price: 2133000,
        image: '/assets/imageProduct/product13.jpg',
        ratting: 5,
        countOfRatting: '1.000',
        to: '/product/adidas-2',
    },
    {
        id: 'adidas-3',
        nameProduct: 'Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product14.jpg',
        ratting: 2,
        countOfRatting: 32,
        to: '/product/adidas-4',
    },
    {
        id: 'adidas-4',
        nameProduct: 'Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product15.jpg',
        ratting: 5,
        countOfRatting: 32,
        to: '/product/adidas-4',
    },
    {
        id: 'adidas-5',
        nameProduct: 'Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product16.jpg',
        ratting: 5,
        countOfRatting: 132,
        to: '/product/adidas-5',
    },
    {
        id: 'adidas-6',
        nameProduct: 'Adidas Neo Grand Court K EF0103',
        price: 321244,
        image: '/assets/imageProduct/product17.jpg',
        ratting: 4.5,
        countOfRatting: 100,
        to: '/product/adidas-6',
    },
];

export const VANS_DATA = [
    {
        id: 'vans-1',
        nameProduct: 'VANS AUTHENTIC BLACK/WHITE',
        price: 1290000,
        image: '/assets/imageProduct/product18.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/vans-1',
        features: [
             'The Vans shoe form fits well on the foot, the stitches are extremely solid and meticulous to ensure the satisfaction of all customers.',
             'VANS AUTHENTIC BLACK / WHITE BLACK / WHITE BLACK and white color are easy to combine with many different outfits according to your preferences to create a beautiful set of clothes when going out, going to school or walking around...',
             'With a youthful, beautiful style, bold style and personality for the wearer. The sole of the shoe has high friction to limit slipping for the user.',
             'Not only for sneaker lovers, the shoes are also suitable for sports enthusiasts with a dynamic and bold fashion style.',
         ],
    },
    {
        id: 'vans-2',
        nameProduct: 'VANS AUTHENTIC BLACK/WHITE',
        price: 1290000,
        image: '/assets/imageProduct/product19.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/vans-2',
        features: [
             'The Vans shoe form fits well on the foot, the stitches are extremely solid and meticulous to ensure the satisfaction of all customers.',
             'VANS AUTHENTIC BLACK / WHITE BLACK / WHITE BLACK and white color are easy to combine with many different outfits according to your preferences to create a beautiful set of clothes when going out, going to school or walking around...',
             'With a youthful, beautiful style, bold style and personality for the wearer. The sole of the shoe has high friction to limit slipping for the user.',
             'Not only for sneaker lovers, the shoes are also suitable for sports enthusiasts with a dynamic and bold fashion style.',
         ],
    },
    {
        id: 'vans-3',
        nameProduct: 'VANS AUTHENTIC BLACK/WHITE',
        price: 1290000,
        image: '/assets/imageProduct/product20.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/vans-3',
        features: [
             'The Vans shoe form fits well on the foot, the stitches are extremely solid and meticulous to ensure the satisfaction of all customers.',
             'VANS AUTHENTIC BLACK / WHITE BLACK / WHITE BLACK and white color are easy to combine with many different outfits according to your preferences to create a beautiful set of clothes when going out, going to school or walking around...',
             'With a youthful, beautiful style, bold style and personality for the wearer. The sole of the shoe has high friction to limit slipping for the user.',
             'Not only for sneaker lovers, the shoes are also suitable for sports enthusiasts with a dynamic and bold fashion style.',
         ],
    },
    {
        id: 'vans-4',
        nameProduct: 'VANS AUTHENTIC BLACK/WHITE',
        price: 1290000,
        image: '/assets/imageProduct/product21.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/vans-4',
        features: [
             'The Vans shoe form fits well on the foot, the stitches are extremely solid and meticulous to ensure the satisfaction of all customers.',
             'VANS AUTHENTIC BLACK / WHITE BLACK / WHITE BLACK and white color are easy to combine with many different outfits according to your preferences to create a beautiful set of clothes when going out, going to school or walking around...',
             'With a youthful, beautiful style, bold style and personality for the wearer. The sole of the shoe has high friction to limit slipping for the user.',
             'Not only for sneaker lovers, the shoes are also suitable for sports enthusiasts with a dynamic and bold fashion style.',
         ],
    },
];

export const MLB_DATA = [
    {
        id: 'mlb-1',
        nameProduct: 'Sneakers unisex Big Ball Chunky Cookie',
        price: 2990000,
        image: '/assets/imageProduct/product22.jpg',
        ratting: 4.8,
        countOfRatting: 282,
        to: '/product/mlb-1',
        features: [
            'Fashionable high heel sneakers',
            'MLB Baseball Association Inspired Design',
            'Resonance with sharp baseball logo lettering detail',
            'Combination of high quality leather with breathable mesh upper',
            'Soft lining, lifting foot shape',
            'Modern colors easily coordinate with many outfits and accessories',
            'Brand Origin: Korea',
        ],
    },
    {
        id: 'mlb-2',
        nameProduct: 'Sneakers unisex Big Ball Chunky Cookie',
        price: 2990000,
        image: '/assets/imageProduct/product23.jpg',
        ratting: 4.2,
        countOfRatting: 1312,
        to: '/product/mlb-2',
        features: [
             'Fashionable high heel sneakers',
             'MLB Baseball Association Inspired Design',
             'Resonance with sharp baseball logo lettering detail',
             'Combination of high quality leather with breathable mesh upper',
             'Soft lining, lifting foot shape',
             'Modern colors easily coordinate with many outfits and accessories',
             'Brand Origin: Korea',
        ],
    },
    {
        id: 'mlb-3',
        nameProduct: 'Sneakers unisex Big Ball Chunky Cookie',
        price: 2990000,
        image: '/assets/imageProduct/product24.jpg',
        ratting: 4.2,
        countOfRatting: 1312,
        to: '/product/mlb-3',
        features: [
             'Fashionable high heel sneakers',
             'MLB Baseball Association Inspired Design',
             'Resonance with sharp baseball logo lettering detail',
             'Combination of high quality leather with breathable mesh upper',
             'Soft lining, lifting foot shape',
             'Modern colors easily coordinate with many outfits and accessories',
             'Brand Origin: Korea',
        ],
    },
];

export const SHOES_DATA = [...NIKE_DATA, ...ADIDAS_DATA, ...VANS_DATA, ...MLB_DATA];

export const MENS_SHIRT = [];

export const T_SHIRT = [
    {
        id: 'tshirt-1',
        nameProduct: 'Recycle Active V2',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product25.jpg',
        ratting: 1,
        countOfRatting: 2,
        to: '/product/tshirt-1',
        features: [
            'Material: 100% Recycle Polyester with 140gsm ultra-lightweight fabric',
            'Suitable for: playing sports',
            'Style: sports t-shirt that fits Vietnamese men',
            'Applied Technology: Wicking (breathable) & Quick-Dry (Quick-Dry)',
            'The worlds leading fabric supplier in the field of sportswear: Promax',
            'Proudly sewing and finishing at Nobland factory, Binh Duong',
        ],
    },
    {
        id: 'tshirt-2',
        nameProduct: 'Marvel Avengers Logo Basics - Cacao',
        price: 299000,
        priceOld: 299000,
        imageHover:
            'https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/cacao_aven_8.jpg',
        image: '/assets/imageProduct/product26.jpg',
        ratting: 2,
        countOfRatting: 3,
        to: '/product/tshirt-2',
        features: [
             'Material: 80% Cotton - 20% Recycle Polyester, 4-way stretch',
             'Is a product of the cooperation between Coolmate and Disney - the owner of the Marvel copyright',
             'Suitable for: work, go out, stay at home',
             'Style: regular fit',
             'Proudly made in Vietnam',
        ],
    },
    {
        id: 'tshirt-3',
        nameProduct: 'Recycle Active V2',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product27.jpg',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/tshirt-3',
        features: [
            'Material: 100% Recycle Polyester with 140gsm ultra-lightweight fabric',
            'Suitable for: playing sports',
            'Style: sports t-shirt that fits Vietnamese men',
            'Applied Technology: Wicking (breathable) & Quick-Dry (Quick-Dry)',
            'The worlds leading fabric supplier in the field of sportswear: Promax',
            'Proudly sewing and finishing at Nobland factory, Binh Duong',
        ],
    },
    {
        id: 'tshirt-4',
        nameProduct: 'Marvel Avengers Logo Basics - Cacao',
        price: 299000,
        priceOld: 299000,
        image: '/assets/imageProduct/product28.jpg',
        ratting: 5,
        countOfRatting: 3,
        to: '/product/tshirt-4',
        features: [
             'Material: 80% Cotton - 20% Recycle Polyester, 4-way stretch',
             'Is a product of the cooperation between Coolmate and Disney - the owner of the Marvel copyright',
             'Suitable for: work, go out, stay at home',
             'Style: regular fit',
             'Proudly made in Vietnam',
        ],
    },
];

export const SHIRT = [
    {
        id: 'shirt-1',
        nameProduct: 'Café-DriS mens long-sleeved shirt ',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product29.jpg',
        ratting: 4.9,
        countOfRatting: 160,
        to: '/product/shirt-1',
        features: [
             'Material: 50% Café - 50% Recycled Poly from PET provides softness and effective deodorization',
             'Suitable for: work, go out',
             'Style: regular fit',
             'Proudly made in Vietnam',
        ],
    },
    {
        id: 'shirt-2',
        nameProduct: 'Excool Limited ',
        price: 259000,
        priceOld: 299000,
        image: '/assets/imageProduct/product30.jpg',
        ratting: 4.5,
        countOfRatting: 17,
        to: '/product/shirt-2',
        features: [
             'Material: 53% Polyester PET high stretch + 47% Polyester PTT Sorona',
             'Suitable for: going out, going to work, participating in polite activities',
             'Style: regular fit',
             'This is the first Japanese style shirt at Coolmate',
             'Proudly sewing and finishing at Nobland factory, Binh Duong',
        ],
    },
    {
        id: 'shirt-3',
        nameProduct: 'Café-DriS mens long-sleeved shirt ',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product31.jpg',
        ratting: 4.9,
        countOfRatting: 160,
        to: '/product/shirt-3',
        features: [
             'Material: 50% Café - 50% Recycled Poly from PET provides softness and effective deodorization',
             'Suitable for: work, go out',
             'Style: regular fit',
             'Proudly made in Vietnam',
        ],
    },
    {
        id: 'shirt-4',
        nameProduct: 'Excool Limited ',
        price: 259000,
        priceOld: 299000,
        image: '/assets/imageProduct/product32.jpg',
        ratting: 4.5,
        countOfRatting: 17,
        to: '/product/shirt-4',
        features: [
             'Material: 53% Polyester PET high stretch + 47% Polyester PTT Sorona',
             'Suitable for: going out, going to work, participating in polite activities',
             'Style: regular fit',
             'This is the first Japanese style shirt at Coolmate',
             'Proudly sewing an finishing at Nobland factory, Binh Duong',
        ],
    },
];

export const POLO_SHIRT = [
    {
        id: 'polo-shirt-1',
        nameProduct: 'Polo Café',
        price: 239000,
        priceOld: 299000,
        image: '/assets/imageProduct/product33.jpg',
        ratting: 4.9,
        countOfRatting: 95,
        to: '/product/polo-shirt-1',
        features: [
             'Material: 50% S.Café + 50% Recycled PET, providing softness and effective deodorization',
             'Application technology: Hydroponic increases the ability to evaporate water from the fabric, helping to dry quickly',
             'Suitable for: work, go out, wear at home',
             'Style: regular fit',
             'High quality factory-made neckline, using Hightwisted 45D/75D yarn to create stretchy and durable form',
             'Proudly made in Vietnam',
        ],
    },
    {
        id: 'polo-shirt-2',
        nameProduct: 'Polo Café',
        price: 239000,
        image: '/assets/imageProduct/product34.jpg',
        ratting: 4.9,
        countOfRatting: 95,
        to: '/product/polo-shirt-2',
        features: [
             'Material: 50% S.Café + 50% Recycled PET, providing softness and effective deodorization',
             'Application technology: Hydroponic increases the ability to evaporate water from the fabric, helping to dry quickly',
             'Suitable for: work, go out, wear at home',
             'Style: regular fit',
             'High quality factory-made neckline, using Hightwisted 45D/75D yarn to create stretchy and durable form',
             'Proudly made in Vietnam',
        ],
    },
];

export const SPORTS_SHIRT = [
    {
        id: 'sport-shirt-1',
        nameProduct: 'Breathable Men Sports Tank Top',
        price: 99000,
        image: '/assets/imageProduct/product35.jpg',
        ratting: 4.5,
        countOfRatting: 209,
        to: '/product/sport-shirt-1',
        features: [
            'Material: 100% Polyester with Quick Dry feature',
            'New Twill (cross) weave for comfortable wearing',
            'Suitable for: going out, going to work, wearing at home',
            'Style: regular fit',
            'Proudly made in Vietnam',
        ],
    },
    {
        id: 'sport-shirt-2',
        nameProduct: 'ProMax-S1',
        price: 149000,
        image: '/assets/imageProduct/product36.jpg',
        ratting: 4.5,
        countOfRatting: 94,
        to: '/product/sport-shirt-2',
        features: [
            'Material: 100% Polyester',
            'Fabric finishing treatment technology: Quick-Dry (quick drying) and Wicking (quick absorbent)',
            'Suitable for: playing sports',
            'Style: regular fit',
            'Proudly sewing and finishing at Nobland factory, Binh Duong',
        ],
    },
];

export const COAT = [
    {
        id: 'coat-1',
        nameProduct: 'HeiQ ViroBlock sports wind jacket, UV resistant & water resistant',
        price: 449000,
        image: '/assets/imageProduct/product37.jpg',
        ratting: 4.8,
        countOfRatting: 340,
        to: '/product/coat-1',
        features: [
            'PRODUCT CAN BE GIVEN WITH ANTI-WASHING MASK',
            'Material: Polyester',
            'Application technology: HeiQ ViroBlock is capable of killing 99.99% of SARS-CoV2 within 30 minutes',
            'Suitable for: sun protection, wind protection',
            'Vest resistant to UV rays',
            'Proudly made in Vietnam',
        ],
    },
    {
        id: 'coat-2',
        nameProduct: 'Men jacket with hood Daily Wear - water repellent, 99% UV protection',
        price: 449000,
        image: '/assets/imageProduct/product38.jpg',
        ratting: 4.8,
        countOfRatting: 17,
        to: '/product/coat-2',
        features: [
            '100% Polyester Material',
            'Application Technology: HeiQ Viro Block',
            'Suitable for: sun protection, wind protection',
            'Style: compact, easy to wear',
            'Proudly made in Vietnam',
        ],
    },
];

export const SHIRTS = [...MENS_SHIRT, ...T_SHIRT, ...SHIRT, ...POLO_SHIRT, ...SPORTS_SHIRT, ...COAT];

export const PRODUCTS = [...SHIRTS, ...HAT_DATA, ...SHOES_DATA];

export const COLOR_SHIRTS = ['white', 'black', 'gray', 'blue', 'yellow']
